# Generated by Django 3.1.6 on 2021-05-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0011_notification_user_g_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_files',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
